####################################################################################################
# Simulation
ndims = 2
equations = "CompressibleEulerMulticomponentEquations"
initial_conditions = "initial_conditions_convergence_test"
surface_flux = "flux_lax_friedrichs"
# Should be activated for EOC test
source_terms = "source_terms_convergence_test"
t_start = 0.0
t_end   = 0.4

####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.3
n_steps_max = 100000
analysis_interval = 100
# extra_analysis_quantities = ["entropy", "energy_total"]

####################################################################################################
# Mesh
n_cells_max = 300000
coordinates_min = [-1.0, -1.0]
coordinates_max =  [1.0, 1.0]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.5, 0.5]},
#   {type = "box", coordinates_min = [-0.1, -0.1], coordinates_max = [0.1, 0.1]},
# ]

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
