####################################################################################################
# Simulation
ndims = 2
equations = "CompressibleEulerMulticomponentEquations"

initial_conditions = "initial_conditions_weak_blast_wave"
surface_flux = "flux_chandrashekar"
volume_flux = "flux_chandrashekar"
t_start = 0.0
t_end   = 0.2



####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "split_form"


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2, -2]
coordinates_max =  [2, 2]
initial_refinement_level = 5


####################################################################################################
# I/O
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
